task 16
maksemuz/tutuer pull request #2
Opened 2017-05-09 14:54 UTC by maksemuz

2017-05-09 18:01 UTC, vkurennov commented on app/views/wagons/_form.html.erb
> +<%= form_for(wagon.becomes(Wagon)) do |f| %>
А зачем передавать @wagon как параметр? Что мешает его использовать напрямую, так же как это в рендере паршала ошибок?

2017-05-09 20:22 UTC, maksemuz commented on app/views/wagons/_form.html.erb
> +<%= form_for(wagon.becomes(Wagon)) do |f| %>
это была проверка работы

2017-05-10 10:09 UTC, vkurennov requested changes

2017-05-10 10:09 UTC, vkurennov commented on app/controllers/railway_stations_controller.rb
> +  before_action :set_railway_station, only: [:show, :edit, :update, :destroy, :update_position]
Что-то я не вижу метода update_position в контроллере (он пока и не нужен), тогда зачем его здесь указывать?

2017-05-10 10:09 UTC, vkurennov commented on app/models/railway_station.rb
> +    rs_object.station_position = position
Вместо присвоения и сохранения, можно использовать метод `udpate`, чтобы все сделать в одну строку.

2017-05-10 10:09 UTC, vkurennov commented on app/models/train.rb
> +    sort_flag ? wagons.sorted_fwd : wagons.sorted_back
Не очень удачное название флага. Оно как бы говорит "сортировать вагоны или нет", а должно "сортировать с головы или с хвоста". Из названия должно быть понятно, что означает true для флага, а что false

2017-05-10 10:09 UTC, vkurennov commented on app/models/wagon.rb
> +  scope :sorted_fwd, -> { order(number: :asc) }
Можно сделать один скоуп с параметром

2017-05-10 10:09 UTC, vkurennov commented on app/views/routes/show.html.erb
> +            <td> <%= station_id.railway_station.position(@route) %> </td>
Почему station_id? там же не id, а сам объект, поэтому должно быть station

2017-05-10 10:09 UTC, vkurennov commented on app/views/trains/_form.html.erb
> +      <%= f.select :sort_flag, [true, false]%>
Тут для пользователя совсем непонятно будет, что это за sort_flag такой

2017-05-10 10:09 UTC, vkurennov commented on app/views/wagons/_form.html.erb
> +<%= form_for(wagon.becomes(Wagon)) do |f| %>
Ну так надо какой-то один способ использовать в итоге: либо wagon, либо @wagon. А то у тебя оба используются

2017-05-10 10:24 UTC, maksemuz commented on app/controllers/railway_stations_controller.rb
> +  before_action :set_railway_station, only: [:show, :edit, :update, :destroy, :update_position]
это я забыл его убрать после экспериментов
убрал

2017-05-10 10:37 UTC, maksemuz commented on app/views/wagons/_form.html.erb
> +<%= form_for(wagon.becomes(Wagon)) do |f| %>
исправил

2017-05-10 10:54 UTC, maksemuz commented on app/models/railway_station.rb
> +    rs_object.station_position = position
да, совсем забыл про этот метод
поправил

2017-05-10 11:03 UTC, maksemuz commented on app/models/train.rb
> +    sort_flag ? wagons.sorted_fwd : wagons.sorted_back
исправил

2017-05-10 11:04 UTC, maksemuz commented on app/views/trains/_form.html.erb
> +      <%= f.select :sort_flag, [true, false]%>
исправил

2017-05-10 12:56 UTC, maksemuz commented on app/models/wagon.rb
> +  scope :sorted_fwd, -> { order(number: :asc) }
была такая мысль, но потом забыл про нее
сделал

2017-05-10 13:39 UTC, maksemuz commented on app/views/routes/show.html.erb
> +            <td> <%= station_id.railway_station.position(@route) %> </td>
да, как-то через задние огороды сделал. но оно работало :)
исправил

2017-05-10 15:43 UTC, vkurennov commented on app/views/routes/show.html.erb
> +            <td> <%= station_id.railway_station.position(@route) %> </td>
Работать-то будет, просто название переменной некорректное

2017-05-10 15:46 UTC, vkurennov approved these changes

2017-05-10 15:46 UTC, vkurennov commented on app/models/railway_station.rb
> +    railway_stations_routes.find_by(route_id: route.id).update(:station_position => position)
Используй всегда новый стиль хеша  - черз двоеточие, а не через хешрокет (`=>`). И, ксати, тут будет ошибка, если find_by не найдет ничего.

2017-05-10 15:46 UTC, vkurennov commented on app/models/train.rb
> +    sort_ascendance ? wagons.sorted_fwd : wagons.sorted_back
Лучше, но я бы называл в терминах предметной области, например, `head_sort`

2017-05-10 15:46 UTC, vkurennov commented on app/views/trains/_form.html.erb
> +      <%= f.label 'Сортировка по возрастанию' %>
Лучше "Нумерация вагонов с головы поезда"

2017-05-10 16:41 UTC, maksemuz commented on app/models/railway_station.rb
> +    railway_stations_routes.find_by(route_id: route.id).update(:station_position => position)
поправил

2017-05-10 16:42 UTC, maksemuz commented on app/models/train.rb
> +    sort_ascendance ? wagons.sorted_fwd : wagons.sorted_back
поправил

2017-05-10 16:44 UTC, maksemuz commented on app/views/trains/_form.html.erb
> +      <%= f.label 'Сортировка по возрастанию' %>
поправил

2017-05-10 16:44 UTC, merged